"""flight logging schema additions

Revision ID: 790f9729d5e5
Revises: a08afa7e88ee
Create Date: 2026-05-09 15:57:51.742132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '790f9729d5e5'
down_revision: Union[str, None] = 'a08afa7e88ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new enum types before they're used in add_column / create_table
    flight_mode_enum = sa.Enum('LIVE', 'SIM_TOFT', name='flightmode')
    capability_area_enum = sa.Enum('MOB', 'FSO', 'ASU', 'SOF', 'PR', 'STW', 'LOG', 'MIW', name='capabilityarea')
    task_grade_enum = sa.Enum('Q', 'CQ', 'U', 'NO', 'NG', name='taskgrade')
    crew_scope_enum = sa.Enum('INDIVIDUAL', 'CREW', name='crewscope')

    flight_mode_enum.create(op.get_bind(), checkfirst=True)
    capability_area_enum.create(op.get_bind(), checkfirst=True)
    task_grade_enum.create(op.get_bind(), checkfirst=True)
    crew_scope_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('cbr_task_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('capability_area', postgresql.ENUM('MOB', 'FSO', 'ASU', 'SOF', 'PR', 'STW', 'LOG', 'MIW', name='capabilityarea', create_type=False), nullable=False),    sa.Column('description', sa.String(), nullable=False),
    sa.Column('crew_scope', postgresql.ENUM('INDIVIDUAL', 'CREW', name='crewscope', create_type=False), nullable=False),    sa.Column('sim_eligible', sa.Boolean(), nullable=False),
    sa.Column('parent_code', sa.String(), nullable=True),
    sa.Column('confers_codes', sa.JSON(), nullable=True),
    sa.Column('min_time_hours', sa.Float(), nullable=False),
    sa.Column('recommended_min_hours', sa.Float(), nullable=True),
    sa.Column('recommended_max_hours', sa.Float(), nullable=True),
    sa.Column('moe_notes', sa.Text(), nullable=True),
    sa.Column('mop_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cbr_task_options_code'), 'cbr_task_options', ['code'], unique=True)
    op.create_table('safety_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sortie_id', sa.Integer(), nullable=True),
    sa.Column('reported_by_person_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('actions_taken', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reported_by_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['sortie_id'], ['sorties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_reports_sortie_id'), 'safety_reports', ['sortie_id'], unique=False)
    op.create_table('sortie_task_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sortie_id', sa.Integer(), nullable=False),
    sa.Column('flight_log_id', sa.Integer(), nullable=False),
    sa.Column('task_code', sa.String(), nullable=False),
    sa.Column('grade', postgresql.ENUM('Q', 'CQ', 'U', 'NO', 'NG', name='taskgrade', create_type=False), nullable=True),    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flight_log_id'], ['flight_logs.id'], ),
    sa.ForeignKeyConstraint(['sortie_id'], ['sorties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_log_id', 'task_code', name='uq_credit_log_task')
    )
    op.create_index(op.f('ix_sortie_task_credits_flight_log_id'), 'sortie_task_credits', ['flight_log_id'], unique=False)
    op.create_index(op.f('ix_sortie_task_credits_sortie_id'), 'sortie_task_credits', ['sortie_id'], unique=False)
    op.add_column('discrepancies', sa.Column('sortie_id', sa.Integer(), nullable=True))
    op.add_column('discrepancies', sa.Column('reported_by_person_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_discrepancies_sortie_id'), 'discrepancies', ['sortie_id'], unique=False)
    op.create_foreign_key(None, 'discrepancies', 'persons', ['reported_by_person_id'], ['id'])
    op.create_foreign_key(None, 'discrepancies', 'sorties', ['sortie_id'], ['id'])
    op.add_column('flight_logs', sa.Column('instructor_remarks', sa.Text(), nullable=True))
    op.add_column('flight_logs', sa.Column('readiness_credits_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sorties', sa.Column('flight_mode', postgresql.ENUM('LIVE', 'SIM_TOFT', name='flightmode', create_type=False), server_default='LIVE', nullable=False))
    op.add_column('sorties', sa.Column('debrief_notes', sa.Text(), nullable=True))
    op.add_column('sorties', sa.Column('simulator_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sorties', 'simulator_id')
    op.drop_column('sorties', 'debrief_notes')
    op.drop_column('sorties', 'flight_mode')
    op.drop_column('flight_logs', 'readiness_credits_count')
    op.drop_column('flight_logs', 'instructor_remarks')
    op.drop_constraint(None, 'discrepancies', type_='foreignkey')
    op.drop_constraint(None, 'discrepancies', type_='foreignkey')
    op.drop_index(op.f('ix_discrepancies_sortie_id'), table_name='discrepancies')
    op.drop_column('discrepancies', 'reported_by_person_id')
    op.drop_column('discrepancies', 'sortie_id')
    op.drop_index(op.f('ix_sortie_task_credits_sortie_id'), table_name='sortie_task_credits')
    op.drop_index(op.f('ix_sortie_task_credits_flight_log_id'), table_name='sortie_task_credits')
    op.drop_table('sortie_task_credits')
    op.drop_index(op.f('ix_safety_reports_sortie_id'), table_name='safety_reports')
    op.drop_table('safety_reports')
    op.drop_index(op.f('ix_cbr_task_options_code'), table_name='cbr_task_options')
    op.drop_table('cbr_task_options')
    # Drop enum types last (after all columns/tables that reference them are gone)
    sa.Enum(name='crewscope').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='taskgrade').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='capabilityarea').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='flightmode').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
