"""initial schema

Revision ID: a08afa7e88ee
Revises: 
Create Date: 2026-05-08 21:43:35.712942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08afa7e88ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bureau_number', sa.String(), nullable=False),
    sa.Column('side_number', sa.String(), nullable=True),
    sa.Column('type_model_series', sa.String(), nullable=False),
    sa.Column('total_airframe_hours', sa.Float(), nullable=False),
    sa.Column('hours_since_phase', sa.Float(), nullable=False),
    sa.Column('phase_interval', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('FMC', 'PMC', 'NMC', 'NMCM', 'NMCS', name='aircraftstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraft_bureau_number'), 'aircraft', ['bureau_number'], unique=True)
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('callsign', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('PILOT', 'AIRCREW', 'SDO', 'TRAINING_O', 'MAINT_CONTROL', 'CO_XO', 'ADMIN', name='role'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_username'), 'persons', ['username'], unique=True)
    op.create_table('syllabus_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('prerequisites', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syllabus_events_code'), 'syllabus_events', ['code'], unique=True)
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('last_event_date', sa.Date(), nullable=True),
    sa.Column('expires_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_person_id'), 'currencies', ['person_id'], unique=False)
    op.create_table('discrepancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('MINOR', 'MAJOR', 'GROUNDING', name='discrepancyseverity'), nullable=False),
    sa.Column('opened_date', sa.DateTime(), nullable=False),
    sa.Column('closed_date', sa.DateTime(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discrepancies_aircraft_id'), 'discrepancies', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_discrepancies_is_open'), 'discrepancies', ['is_open'], unique=False)
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('qual_code', sa.String(), nullable=False),
    sa.Column('qualified_date', sa.Date(), nullable=True),
    sa.Column('expires_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualifications_person_id'), 'qualifications', ['person_id'], unique=False)
    op.create_table('sorties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_code', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('brief_time', sa.DateTime(), nullable=True),
    sa.Column('takeoff_time', sa.DateTime(), nullable=True),
    sa.Column('land_time', sa.DateTime(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('day_hours', sa.Float(), nullable=True),
    sa.Column('night_hours', sa.Float(), nullable=True),
    sa.Column('nvg_hours', sa.Float(), nullable=True),
    sa.Column('instrument_hours', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sorties_aircraft_id'), 'sorties', ['aircraft_id'], unique=False)
    op.create_table('flight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sortie_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('crew_position', sa.Enum('HAC', 'H2P', 'H2P_U', 'CREW_CHIEF', 'AIRCREW', 'AWS', name='crewposition'), nullable=False),
    sa.Column('hours_logged', sa.Float(), nullable=True),
    sa.Column('syllabus_event_completed', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['sortie_id'], ['sorties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_logs_person_id'), 'flight_logs', ['person_id'], unique=False)
    op.create_index(op.f('ix_flight_logs_sortie_id'), 'flight_logs', ['sortie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_logs_sortie_id'), table_name='flight_logs')
    op.drop_index(op.f('ix_flight_logs_person_id'), table_name='flight_logs')
    op.drop_table('flight_logs')
    op.drop_index(op.f('ix_sorties_aircraft_id'), table_name='sorties')
    op.drop_table('sorties')
    op.drop_index(op.f('ix_qualifications_person_id'), table_name='qualifications')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_discrepancies_is_open'), table_name='discrepancies')
    op.drop_index(op.f('ix_discrepancies_aircraft_id'), table_name='discrepancies')
    op.drop_table('discrepancies')
    op.drop_index(op.f('ix_currencies_person_id'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_syllabus_events_code'), table_name='syllabus_events')
    op.drop_table('syllabus_events')
    op.drop_index(op.f('ix_persons_username'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_aircraft_bureau_number'), table_name='aircraft')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
