"""HSC/MH-60S CBR task catalog shaped to Wing Training Manual Enclosure 2.

This is an unclassified, paraphrased demonstration catalog — not a verbatim
reproduction of CHSCWPINST 3500.1F Enclosure 2. Task codes, areas, and anchor
designations are structured for realistic WTM readiness math and demos.

Used by ``seed.py`` and readiness integrity tests.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import FrozenSet, List, Tuple

from app.models.enums import CapabilityArea, CrewScope


@dataclass(frozen=True)
class CbrTaskSpec:
    code: str
    capability_area: CapabilityArea
    description: str
    crew_scope: CrewScope
    sim_eligible: bool
    min_time_hours: float
    confers_codes: List[str]
    moe_notes: str
    mop_notes: str
    is_anchor_task: bool = False


# Anchor tasks drive T-1/T-2/T-3 gates (Appendix D area rollups).
ANCHOR_TASK_CODES: FrozenSet[str] = frozenset({
    "ASU 201",
    "ASU 207",
    "FSO 207",
    "FSO 209",
    "LOG 201",
    "MIW 203",
    "MIW 205",
    "MOB 203",
    "MOB 204",
    "MOB 209",
    "PR 201",
    "SOF 207",
    "STW 210",
})

CBR_TASK_SPECS: Tuple[CbrTaskSpec, ...] = (
    CbrTaskSpec(
        code="MOB 201",
        capability_area=CapabilityArea.MOB,
        description='NATOPS Check — Aircrew demonstrate proficiency per NATOPS procedures; evaluated by designated check aircrewman.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=False,
        min_time_hours=1.5,
        confers_codes=[],
        moe_notes='Aircrew demonstrate NATOPS-standard emergency procedures and systems knowledge.',
        mop_notes='Complete all required EP demonstrations; verbal/written exam as required by NATOPS.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MOB 202",
        capability_area=CapabilityArea.MOB,
        description='Emergency Procedure Training — Crew execute simulated emergency procedures in flight or simulator.',
        crew_scope=CrewScope.CREW,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew correctly identify, communicate, and execute all assigned EP scenarios.',
        mop_notes='Execute each EP per NATOPS checklist; HAC grades crew actions on task/condition/standard.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MOB 203",
        capability_area=CapabilityArea.MOB,
        description='Basic Flight / FAM / FCF — Crew demonstrate basic airmanship during familiarization, proficiency, or functional check flight.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.5,
        confers_codes=[],
        moe_notes='Crew maintain aircraft control within NATOPS limits throughout all maneuvers.',
        mop_notes='Complete all planned profiles; no deviations outside NATOPS limits; HAC debriefs crew.',
        is_anchor_task=True,
    ),
    CbrTaskSpec(
        code="MOB 204",
        capability_area=CapabilityArea.MOB,
        description='Night Flight — Crew demonstrate proficiency during unaided or NVG night operations.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=2.0,
        confers_codes=['MOB 203'],
        moe_notes='Crew maintain situational awareness and aircraft control during night operations.',
        mop_notes='Complete all planned night profiles; NVG goggle ops IAW NATOPS Chapter 7 if applicable.',
        is_anchor_task=True,
    ),
    CbrTaskSpec(
        code="MOB 205",
        capability_area=CapabilityArea.MOB,
        description='Air-Capable Ship Recovery Day — Pilot demonstrates proficiency in day shipboard approaches and deck landings.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Pilot executes stabilized approach to within NATOPS tolerances on each approach.',
        mop_notes='Minimum 6 approaches; grade each approach per NATOPS T&R; HAC certifies completion.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MOB 209",
        capability_area=CapabilityArea.MOB,
        description='Instrument Check — Aircrew demonstrate proficiency in IMC and instrument approach procedures.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=True,
        min_time_hours=1.0,
        confers_codes=[],
        moe_notes='Aircrew fly all assigned instrument approach categories within NATOPS tolerances.',
        mop_notes='Complete ILS, RNAV, and partial-panel approaches; HAC or IP grades each approach.',
        is_anchor_task=True,
    ),
    CbrTaskSpec(
        code="MOB 211",
        capability_area=CapabilityArea.MOB,
        description='Terminal Area Operations — Crew demonstrate proficiency in confined area and pinnacle landing operations.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew completes terminal area profiles without exceeding aircraft or site limitations.',
        mop_notes='Conduct minimum one confined area approach/departure; crew brief/debrief required.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MOB 214",
        capability_area=CapabilityArea.MOB,
        description='Formation Flight — Crew demonstrate proficiency in multi-aircraft formation operations.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew maintains assigned position within NATOPS formation parameters throughout flight.',
        mop_notes='Lead and wing phases; all crew demonstrate comm discipline and position awareness.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="FSO 207",
        capability_area=CapabilityArea.FSO,
        description='Live Hoist — Crew execute external rescue hoist operations with a live swimmer or load.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew successfully deploys/recovers load or SAR swimmer within NATOPS weight and speed limits.',
        mop_notes='Minimum two hoist cycles with live load; AWS grades hook-up procedure and crew coordination.',
        is_anchor_task=True,
    ),
    CbrTaskSpec(
        code="FSO 208",
        capability_area=CapabilityArea.FSO,
        description='Hoist Training — Crew execute hoist training with a dummy load or training device.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew demonstrates correct hoist procedures and emergency actions with training load.',
        mop_notes='Demonstrate hook-up, hoist operation, and recovery; practice emergency jettison procedure.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="FSO 209",
        capability_area=CapabilityArea.FSO,
        description='Search and Rescue — Crew execute a search pattern and execute survivor recovery in a SAR scenario.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.0,
        confers_codes=[],
        moe_notes='Crew locates simulated survivor within planned search area and executes recovery.',
        mop_notes='Execute assigned search pattern; demonstrate datum run procedures; recover survivor via hoist.',
        is_anchor_task=True,
    ),
    CbrTaskSpec(
        code="ASU 201",
        capability_area=CapabilityArea.ASU,
        description='CSW Pattern — Pilot/crew execute a coordinated surface warfare engagement pattern against a surface target.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew executes coordinated search/strike pattern and correctly employs sensors against surface targets.',
        mop_notes='Complete all assigned CSW pattern phases; sensor employment grades per ASU T&R criteria.',
        is_anchor_task=True,
    ),
    CbrTaskSpec(
        code="ASU 206",
        capability_area=CapabilityArea.ASU,
        description='MTS Employment — Aircrew employ the Multi-spectral Targeting System against surface targets.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='AWS/aircrew acquires and tracks assigned targets with MTS within ASU engagement criteria.',
        mop_notes='Demonstrate MTS initialization, target acquisition, tracking, and handoff; debrief grade assigned.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="ASU 207",
        capability_area=CapabilityArea.ASU,
        description='SCAR — Crew execute a Strike Coordination and Reconnaissance mission in support of surface forces.',
        crew_scope=CrewScope.CREW,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew successfully coordinates with surface units and provides reconnaissance products.',
        mop_notes='Complete full SCAR profile; comm plan executed; crew debrief includes target product assessment.',
        is_anchor_task=True,
    ),
    CbrTaskSpec(
        code="SOF 207",
        capability_area=CapabilityArea.SOF,
        description='SOF Insertion/Extraction — Crew insert or extract special operations forces via fast-rope, SPIE, or hover delivery.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew successfully inserts/extracts SOF element within time and accuracy parameters.',
        mop_notes='Execute insertion or extraction IAW SOF T&R criteria; HAC grades crew coordination and airspeed control.',
        is_anchor_task=True,
    ),
    CbrTaskSpec(
        code="PR 201",
        capability_area=CapabilityArea.PR,
        description='Combat Search and Rescue — Crew executes recovery of isolated personnel in a contested environment.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew establishes comm with isolated personnel, executes recovery under threat environment constraints.',
        mop_notes='Authentication, comm relay, threat assessment, and survivor recovery completed per PR T&R criteria.',
        is_anchor_task=True,
    ),
    CbrTaskSpec(
        code="STW 210",
        capability_area=CapabilityArea.STW,
        description='Large Force Exercise — Crew participates in a large force strike exercise with multi-unit coordination.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew integrates with strike package within EMCON and timing parameters.',
        mop_notes='Complete all assigned LFE tasking; mission commander debrief; T/M/S grades assigned per exercise criteria.',
        is_anchor_task=True,
    ),
    CbrTaskSpec(
        code="LOG 201",
        capability_area=CapabilityArea.LOG,
        description='Day VERTREP — Crew execute vertical replenishment operations transferring cargo between ships.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew completes all assigned VERTREP cycles within weight limits and ship course/speed parameters.',
        mop_notes='Demonstrate cargo hook-up, transfer, and release procedures; AWS grades sling load operations.',
        is_anchor_task=True,
    ),
    CbrTaskSpec(
        code="MIW 203",
        capability_area=CapabilityArea.MIW,
        description='ALMDS Simulator Day — Aircrew demonstrate proficiency with the Airborne Laser Mine Detection System in a simulator.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Aircrew demonstrates ALMDS system initialization, sweep pattern execution, and contact classification.',
        mop_notes='Complete simulator ALMDS profile; system setup, sweep pattern, and contact report graded per MIW T&R.',
        is_anchor_task=True,
    ),
    CbrTaskSpec(
        code="MIW 205",
        capability_area=CapabilityArea.MIW,
        description='ALMDS Employment Day — Crew employ ALMDS in flight against a real or simulated minefield during daylight.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew successfully executes ALMDS lane sweep and generates contact report within time parameters.',
        mop_notes='Execute full ALMDS lane; report contacts per MIW T&R criteria; post-mission data download graded.',
        is_anchor_task=True,
    ),
    CbrTaskSpec(
        code="MOB 206",
        capability_area=CapabilityArea.MOB,
        description='Overwater Flight — Crew demonstrate proficiency during overwater transit and ditching procedures.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.0,
        confers_codes=['MOB 203'],
        moe_notes='Crew maintains aircraft control and executes ditching EPs per NATOPS during overwater profiles.',
        mop_notes='Complete overwater transit profile; crew brief ditching EPs; HAC grades crew coordination.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MOB 207",
        capability_area=CapabilityArea.MOB,
        description='Confined Area Day — Crew demonstrate day confined-area takeoff and landing operations.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['MOB 203'],
        moe_notes='Crew completes confined area profiles without exceeding site or aircraft limitations.',
        mop_notes='Minimum one confined area approach/departure; crew debrief required.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MOB 208",
        capability_area=CapabilityArea.MOB,
        description='Confined Area Night — Crew demonstrate NVG confined-area operations.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['MOB 204'],
        moe_notes='Crew maintains SA and aircraft control during NVG confined-area profiles.',
        mop_notes='Complete NVG confined area profile IAW NATOPS Chapter 7.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MOB 210",
        capability_area=CapabilityArea.MOB,
        description='External Load Day — Crew demonstrate external cargo sling load operations in daylight.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew completes external load cycles within weight and airspeed limits.',
        mop_notes='Demonstrate hook-up, lift, transit, and release; AWS grades sling load procedures.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="FSO 201",
        capability_area=CapabilityArea.FSO,
        description='Overwater SAR Pattern — Crew execute overwater search pattern and datum procedures.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew establishes datum and executes assigned search pattern within planned area.',
        mop_notes='Complete datum run and search legs; comm plan executed per FSO T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="FSO 202",
        capability_area=CapabilityArea.FSO,
        description='CSAR Overland — Crew execute deliberate combat search and rescue overland profile.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.0,
        confers_codes=[],
        moe_notes='Crew authenticates isolated personnel and executes recovery under threat constraints.',
        mop_notes='Authentication, threat assessment, and recovery completed per FSO/PR criteria.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="FSO 203",
        capability_area=CapabilityArea.FSO,
        description='Vertrep SAR — Crew combine VERTREP and SAR swimmer deployment in a composite scenario.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew coordinates cargo transfer and swimmer deployment without exceeding limits.',
        mop_notes='Execute combined profile; AWS grades hook-up and swimmer coordination.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="FSO 204",
        capability_area=CapabilityArea.FSO,
        description='Night Hoist — Crew execute external hoist operations at night with NVG.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['FSO 207'],
        moe_notes='Crew successfully deploys/recovers load at night within NATOPS limits.',
        mop_notes='Minimum two NVG hoist cycles; AWS grades crew coordination.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="FSO 205",
        capability_area=CapabilityArea.FSO,
        description='Fast Rope Insertion — Crew insert personnel via fast-rope in a FSO support scenario.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew maintains hover parameters and inserts personnel within time/accuracy limits.',
        mop_notes='Execute fast-rope insertion IAW FSO T&R; HAC grades airspeed and hover control.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="FSO 206",
        capability_area=CapabilityArea.FSO,
        description='SPIE Extraction — Crew extract personnel via Special Patrol Insertion/Extraction rig.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew successfully extracts personnel via SPIE within NATOPS weight limits.',
        mop_notes='Demonstrate SPIE rigging, extraction, and recovery; AWS grades procedures.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="ASU 202",
        capability_area=CapabilityArea.ASU,
        description='Strafe Dry — Pilot/crew execute dry strafe pattern against surface target.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew executes strafe pattern within ASU engagement parameters.',
        mop_notes='Complete dry strafe profile; sensor/weapon employment graded per ASU T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="ASU 203",
        capability_area=CapabilityArea.ASU,
        description='Strafe Live — Pilot/crew execute live strafe engagement against authorized target.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['ASU 202'],
        moe_notes='Crew executes live strafe within safety and engagement parameters.',
        mop_notes='Complete live strafe profile; range safety and engagement criteria met.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="ASU 204",
        capability_area=CapabilityArea.ASU,
        description='Rocket Dry — Crew execute dry rocket engagement pattern.',
        crew_scope=CrewScope.CREW,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew executes rocket pattern within ASU engagement criteria.',
        mop_notes='Complete dry rocket profile; crew coordination graded per ASU T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="ASU 205",
        capability_area=CapabilityArea.ASU,
        description='Rocket Live — Crew execute live rocket engagement.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['ASU 204'],
        moe_notes='Crew executes live rocket engagement within safety parameters.',
        mop_notes='Complete live rocket profile; range safety criteria met.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="ASU 208",
        capability_area=CapabilityArea.ASU,
        description='Armed Reconnaissance — Crew conduct armed reconnaissance in support of surface forces.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.0,
        confers_codes=[],
        moe_notes='Crew provides timely reconnaissance products to supported unit.',
        mop_notes='Complete armed recon profile; comm and reporting per ASU T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="SOF 201",
        capability_area=CapabilityArea.SOF,
        description='SOF Infiltration Day — Crew infiltrate SOF element via hover delivery in daylight.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew inserts SOF element within time and accuracy parameters.',
        mop_notes='Execute day infiltration IAW SOF T&R; HAC grades hover and airspeed control.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="SOF 202",
        capability_area=CapabilityArea.SOF,
        description='SOF Infiltration Night — Crew infiltrate SOF element via NVG hover delivery.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['SOF 201'],
        moe_notes='Crew inserts SOF element at night within NATOPS NVG limits.',
        mop_notes='Execute NVG infiltration profile; crew coordination graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="SOF 203",
        capability_area=CapabilityArea.SOF,
        description='SOF Extraction Day — Crew extract SOF element via fast-rope or hover pickup.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew extracts SOF element within planned time parameters.',
        mop_notes='Execute day extraction IAW SOF T&R criteria.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="SOF 204",
        capability_area=CapabilityArea.SOF,
        description='SOF Extraction Night — Crew extract SOF element during NVG operations.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['SOF 203'],
        moe_notes='Crew extracts SOF element at night within NVG parameters.',
        mop_notes='Execute NVG extraction profile; HAC grades crew coordination.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="SOF 205",
        capability_area=CapabilityArea.SOF,
        description='Tactical Air Landing — Crew land at unprepared site in support of SOF operations.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew completes tactical landing without exceeding site limitations.',
        mop_notes='Site survey, approach, and departure per SOF T&R; crew debrief required.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="SOF 206",
        capability_area=CapabilityArea.SOF,
        description='Urban SOF Support — Crew support SOF operations in urban/confined environment.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew maintains comm and aircraft control in urban support profile.',
        mop_notes='Execute urban support scenario; threat and comm plan per SOF T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="PR 202",
        capability_area=CapabilityArea.PR,
        description='Overwater CSAR — Crew execute overwater combat search and rescue recovery.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.0,
        confers_codes=[],
        moe_notes='Crew locates and recovers isolated personnel in overwater environment.',
        mop_notes='Execute overwater CSAR profile; datum and recovery per PR T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="PR 203",
        capability_area=CapabilityArea.PR,
        description='Deliberate CSAR Overland — Crew execute deliberate overland CSAR mission.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.0,
        confers_codes=[],
        moe_notes='Crew authenticates and recovers isolated personnel in contested overland environment.',
        mop_notes='Authentication, threat assessment, and recovery per PR T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="PR 204",
        capability_area=CapabilityArea.PR,
        description='CSAR Simulator — Crew execute CSAR scenario in simulator or training device.',
        crew_scope=CrewScope.CREW,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew demonstrates CSAR comm, authentication, and recovery procedures.',
        mop_notes='Complete simulator CSAR profile; all EPs and comm procedures graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="PR 205",
        capability_area=CapabilityArea.PR,
        description='Isolated Personnel Authentication — Crew demonstrate authentication procedures for isolated personnel.',
        crew_scope=CrewScope.CREW,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew correctly authenticates isolated personnel per PR comm plan.',
        mop_notes='Execute authentication drill; comm relay and challenge/response graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="STW 201",
        capability_area=CapabilityArea.STW,
        description='Strike Coordination — Crew coordinate strike package timing and EMCON.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew integrates with strike package within timing parameters.',
        mop_notes='Complete strike coordination profile; mission commander debrief.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="STW 202",
        capability_area=CapabilityArea.STW,
        description='Time-Sensitive Targeting — Crew support time-sensitive targeting mission.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew provides timely targeting support to supported unit.',
        mop_notes='Execute TST profile; comm and targeting product per STW T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="STW 203",
        capability_area=CapabilityArea.STW,
        description='Armed Escort — Crew provide armed escort for surface or air assets.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew maintains escort position and threat response per STW criteria.',
        mop_notes='Complete armed escort profile; threat reaction graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="STW 204",
        capability_area=CapabilityArea.STW,
        description='Battle Damage Assessment — Crew conduct BDA after strike operations.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew provides timely and accurate BDA to supported commander.',
        mop_notes='Execute BDA profile; imagery and reporting per STW T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="STW 205",
        capability_area=CapabilityArea.STW,
        description='Strike Package Integration — Crew integrate into multi-unit strike package.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew maintains EMCON and timing within strike package parameters.',
        mop_notes='Complete integration profile; debrief includes package coordination assessment.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="STW 206",
        capability_area=CapabilityArea.STW,
        description='Close Air Support — Crew provide CAS in support of ground forces.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.0,
        confers_codes=[],
        moe_notes='Crew provides timely CAS within ROE and comm parameters.',
        mop_notes='Execute CAS profile; 9-line and comm plan per STW T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="STW 207",
        capability_area=CapabilityArea.STW,
        description='Armed Reconnaissance Strike — Crew conduct armed recon with strike authority.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.0,
        confers_codes=[],
        moe_notes='Crew identifies targets and executes strike within ROE.',
        mop_notes='Complete armed recon/strike profile; BDA and reporting graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="STW 208",
        capability_area=CapabilityArea.STW,
        description='Night Strike — Crew participate in night strike exercise.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['STW 201'],
        moe_notes='Crew integrates with night strike package within NVG parameters.',
        mop_notes='Complete night strike profile; NVG ops IAW NATOPS.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="STW 209",
        capability_area=CapabilityArea.STW,
        description='Exercise Strike — Crew participate in fleet exercise strike scenario.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew completes assigned exercise strike tasking.',
        mop_notes='Exercise debrief; T/M/S grades per exercise criteria.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="LOG 202",
        capability_area=CapabilityArea.LOG,
        description='Night VERTREP — Crew execute vertical replenishment at night.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['LOG 201'],
        moe_notes='Crew completes VERTREP cycles at night within ship parameters.',
        mop_notes='Demonstrate NVG VERTREP procedures; AWS grades sling load ops.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="LOG 203",
        capability_area=CapabilityArea.LOG,
        description='VERTREP Simulator — Crew practice VERTREP procedures in simulator.',
        crew_scope=CrewScope.CREW,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew demonstrates VERTREP hook-up and transfer procedures.',
        mop_notes='Complete simulator VERTREP profile; procedures graded per LOG T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="LOG 204",
        capability_area=CapabilityArea.LOG,
        description='Cargo Transfer — Crew transfer internal cargo between ships via VERTREP.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew completes cargo transfer within weight and timing limits.',
        mop_notes='Execute cargo transfer profile; AWS grades procedures.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MIW 201",
        capability_area=CapabilityArea.MIW,
        description='MIW Brief — Aircrew demonstrate mine warfare threat recognition and reporting.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Aircrew correctly identifies mine threats and reports per MIW doctrine.',
        mop_notes='Complete MIW threat brief and recognition drill.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MIW 202",
        capability_area=CapabilityArea.MIW,
        description='ALMDS Simulator Night — Aircrew demonstrate ALMDS operations at night in simulator.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=['MIW 203'],
        moe_notes='Aircrew executes ALMDS night sweep pattern and contact classification.',
        mop_notes='Complete night simulator ALMDS profile per MIW T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MIW 204",
        capability_area=CapabilityArea.MIW,
        description='ALMDS Employment Night — Crew employ ALMDS during night flight operations.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['MIW 205'],
        moe_notes='Crew executes night ALMDS lane sweep and contact report.',
        mop_notes='Execute night ALMDS profile; post-mission data download graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MIW 206",
        capability_area=CapabilityArea.MIW,
        description='Mine Countermeasures Support — Crew support MCM unit with ALMDS lane clearance.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.0,
        confers_codes=[],
        moe_notes='Crew provides timely ALMDS products to MCM commander.',
        mop_notes='Execute MCM support profile; lane clearance and reporting per MIW T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MOB 212",
        capability_area=CapabilityArea.MOB,
        description='Shipboard Night Recovery — Pilot demonstrates night shipboard approaches and deck landings with NVG.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['MOB 205'],
        moe_notes='Pilot executes stabilized NVG shipboard approaches within NATOPS tolerances.',
        mop_notes='Minimum 6 night approaches; grade each approach per NATOPS T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MOB 213",
        capability_area=CapabilityArea.MOB,
        description='Instrument Approach Proficiency — Aircrew execute instrument approaches to published minima.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=['MOB 209'],
        moe_notes='Aircrew fly assigned approach categories within NATOPS tolerances.',
        mop_notes='Complete ILS/RNAV approaches; IP grades each approach.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MOB 215",
        capability_area=CapabilityArea.MOB,
        description='Formation Night — Crew demonstrate NVG multi-aircraft formation operations.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['MOB 214'],
        moe_notes='Crew maintains formation position within NATOPS NVG parameters.',
        mop_notes='Lead and wing night phases; comm discipline graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MOB 216",
        capability_area=CapabilityArea.MOB,
        description='Cross-Country / Navigation — Crew execute long-range navigation and fuel planning profile.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.0,
        confers_codes=['MOB 203'],
        moe_notes='Crew completes navigation profile with accurate ETA and fuel remaining.',
        mop_notes='Complete planned route; HAC grades nav and fuel management.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MOB 217",
        capability_area=CapabilityArea.MOB,
        description='Mountain / High DA Operations — Crew operate in high density altitude environment.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['MOB 203'],
        moe_notes='Crew maintains performance awareness and power management at high DA.',
        mop_notes='Complete high-DA profile; power checks and contingency plans debriefed.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MOB 218",
        capability_area=CapabilityArea.MOB,
        description='Shipboard VERTREP Day — Crew demonstrate day shipboard vertical replenishment approaches.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew completes shipboard VERTREP approaches within ship course/speed parameters.',
        mop_notes='Demonstrate approach, station-keeping, and departure IAW ship NATOPS.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="FSO 210",
        capability_area=CapabilityArea.FSO,
        description='SAR Swimmer Deployment — Crew deploy and recover SAR swimmer in training scenario.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['FSO 207'],
        moe_notes='Crew deploys/recovers SAR swimmer within NATOPS weight and speed limits.',
        mop_notes='Minimum two swimmer cycles; AWS grades deployment procedures.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="FSO 211",
        capability_area=CapabilityArea.FSO,
        description='Multi-Unit SAR Coordination — Crew coordinate SAR with multiple rescue units.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['FSO 209'],
        moe_notes='Crew maintains comm plan and SAR coordination with supporting units.',
        mop_notes='Execute multi-unit SAR scenario; OSC/comm procedures graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="FSO 212",
        capability_area=CapabilityArea.FSO,
        description='Night Overwater SAR — Crew execute overwater SAR pattern at night with NVG.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.0,
        confers_codes=['FSO 201'],
        moe_notes='Crew establishes datum and executes night overwater search pattern.',
        mop_notes='Complete night overwater SAR profile; NVG ops IAW NATOPS Chapter 7.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="FSO 213",
        capability_area=CapabilityArea.FSO,
        description='Hoist Emergency Procedures — Crew practice hoist emergency and jettison procedures.',
        crew_scope=CrewScope.CREW,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=['FSO 208'],
        moe_notes='Crew correctly executes hoist emergency actions and jettison procedures.',
        mop_notes='Demonstrate emergency procedures in flight or simulator; AWS grades actions.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="ASU 209",
        capability_area=CapabilityArea.ASU,
        description='Surface Search Pattern — Crew execute surface search pattern with sensor employment.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew executes assigned surface search pattern and reports contacts.',
        mop_notes='Complete search pattern; sensor employment graded per ASU T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="ASU 210",
        capability_area=CapabilityArea.ASU,
        description='Night CSW Pattern — Pilot/crew execute night surface warfare pattern with NVG.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['ASU 201'],
        moe_notes='Crew executes night CSW pattern within engagement parameters.',
        mop_notes='Complete night CSW profile; NVG sensor employment graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="ASU 211",
        capability_area=CapabilityArea.ASU,
        description='Target Handoff — Crew execute sensor-to-shooter target handoff.',
        crew_scope=CrewScope.CREW,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=['ASU 206'],
        moe_notes='Crew completes timely and accurate target handoff to supported unit.',
        mop_notes='Demonstrate handoff format and confirmation; debrief grade assigned.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="ASU 212",
        capability_area=CapabilityArea.ASU,
        description='Missile Simulation / Engagement — Crew execute simulated anti-surface missile employment profile.',
        crew_scope=CrewScope.CREW,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew executes engagement profile within ASU ROE and parameters.',
        mop_notes='Complete simulated engagement; weapon employment graded per ASU T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="SOF 208",
        capability_area=CapabilityArea.SOF,
        description='SOF Escort / Security — Crew provide airborne security for SOF ground element.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew maintains orbit and threat response in support of SOF element.',
        mop_notes='Execute security profile; threat reaction and comm plan graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="SOF 209",
        capability_area=CapabilityArea.SOF,
        description='Maritime SOF Insertion — Crew insert SOF element to maritime platform or small craft.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['SOF 201'],
        moe_notes='Crew inserts SOF element to maritime target within time/accuracy parameters.',
        mop_notes='Execute maritime insertion IAW SOF T&R; hover and airspeed control graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="SOF 210",
        capability_area=CapabilityArea.SOF,
        description='SOF Night Fast Rope — Crew insert SOF via NVG fast-rope.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['SOF 201'],
        moe_notes='Crew maintains hover and inserts SOF via fast-rope at night.',
        mop_notes='Execute NVG fast-rope profile; crew coordination graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="PR 206",
        capability_area=CapabilityArea.PR,
        description='CSAR Package Integration — Crew integrate into multi-unit CSAR package.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['PR 201'],
        moe_notes='Crew maintains timing and EMCON within CSAR package parameters.',
        mop_notes='Complete package integration profile; mission commander debrief.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="PR 207",
        capability_area=CapabilityArea.PR,
        description='Night CSAR Overland — Crew execute night deliberate overland CSAR recovery.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.0,
        confers_codes=['PR 203'],
        moe_notes='Crew authenticates and recovers isolated personnel at night under threat constraints.',
        mop_notes='Execute night overland CSAR; NVG ops and recovery per PR T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="PR 208",
        capability_area=CapabilityArea.PR,
        description='Survivor Signaling / Marking — Crew demonstrate survivor signaling and marking procedures.',
        crew_scope=CrewScope.CREW,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew correctly interprets survivor signals and marks position for recovery.',
        mop_notes='Execute signaling drill; marking and report graded per PR doctrine.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="STW 211",
        capability_area=CapabilityArea.STW,
        description='SEAD Support — Crew support suppression of enemy air defenses scenario.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew integrates SEAD support tasking within package timing.',
        mop_notes='Complete SEAD support profile; threat and timing debrief.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="STW 212",
        capability_area=CapabilityArea.STW,
        description='Joint Fires Integration — Crew integrate with joint fires in support of ground forces.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['STW 206'],
        moe_notes='Crew provides timely joint fires support within ROE.',
        mop_notes='Execute joint fires profile; 9-line and clearance graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="STW 213",
        capability_area=CapabilityArea.STW,
        description='Dynamic Targeting — Crew execute dynamic targeting against fleeting targets.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['STW 202'],
        moe_notes='Crew identifies and engages fleeting targets within ROE and time parameters.',
        mop_notes='Complete dynamic targeting profile; BDA and reporting graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="LOG 205",
        capability_area=CapabilityArea.LOG,
        description='External Cargo Day — Crew transfer external cargo between shore sites.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew completes external cargo cycles within weight limits.',
        mop_notes='Demonstrate hook-up, transit, and release; AWS grades procedures.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="LOG 206",
        capability_area=CapabilityArea.LOG,
        description='Ship-to-Shore Logistics — Crew execute logistics transfer from ship to shore site.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['LOG 201'],
        moe_notes='Crew completes ship-to-shore transfer within timing parameters.',
        mop_notes='Execute logistics profile; ship and shore coordination graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="LOG 207",
        capability_area=CapabilityArea.LOG,
        description='Emergency Logistics / CASEVAC Support — Crew provide emergency logistics or CASEVAC support.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew executes emergency logistics/CASEVAC profile with correct priorities.',
        mop_notes='Complete emergency logistics scenario; prioritization and timing graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="LOG 208",
        capability_area=CapabilityArea.LOG,
        description='Multi-Ship VERTREP — Crew support multi-ship VERTREP evolution.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=1.0,
        confers_codes=['LOG 201'],
        moe_notes='Crew coordinates multi-ship VERTREP without exceeding ship parameters.',
        mop_notes='Execute multi-ship VERTREP profile; AWS grades sling load and coordination.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MIW 207",
        capability_area=CapabilityArea.MIW,
        description='AMNS Simulator — Aircrew demonstrate Airborne Mine Neutralization System in simulator.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=True,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Aircrew demonstrates AMNS initialization and engagement sequence.',
        mop_notes='Complete simulator AMNS profile; system setup and engagement graded per MIW T&R.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MIW 208",
        capability_area=CapabilityArea.MIW,
        description='AMNS Employment Day — Crew employ AMNS in flight against simulated mine targets.',
        crew_scope=CrewScope.INDIVIDUAL,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['MIW 207'],
        moe_notes='Crew successfully executes AMNS engagement and reports results.',
        mop_notes='Execute AMNS profile; post-mission data and reporting graded.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MIW 209",
        capability_area=CapabilityArea.MIW,
        description='Mine Warfare Coordination — Crew coordinate MIW products with MCM commander.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=[],
        moe_notes='Crew provides timely MIW products and coordination to MCM unit.',
        mop_notes='Execute coordination profile; reporting format graded per MIW doctrine.',
        is_anchor_task=False,
    ),
    CbrTaskSpec(
        code="MIW 210",
        capability_area=CapabilityArea.MIW,
        description='Night MIW Support — Crew support night mine warfare operations with sensors.',
        crew_scope=CrewScope.CREW,
        sim_eligible=False,
        min_time_hours=0.5,
        confers_codes=['MIW 204'],
        moe_notes='Crew maintains night MIW support orbit and sensor employment.',
        mop_notes='Execute night MIW support profile; NVG and sensor employment graded.',
        is_anchor_task=False,
    ),
)

# Per-area T-rating windows and Table B-2 currency gates (Appendix D-aligned).
AREA_CONFIG_SPECS: Tuple[Tuple[CapabilityArea, str, int, int, List[str], List[str]], ...] = (
    (CapabilityArea.MOB, "Mobility", 180, 365, ['NIGHT_NVD'], []),
    (CapabilityArea.FSO, "Fleet Support Ops", 180, 365, ['CSTRS_WINCH'], []),
    (CapabilityArea.ASU, "Anti-Surface Warfare", 180, 365, ['CSW', 'STRAFE_DRY'], []),
    (CapabilityArea.SOF, "Special Operations Forces", 180, 365, [], []),
    (CapabilityArea.PR, "Personnel Recovery", 180, 365, [], []),
    (CapabilityArea.STW, "Strike Warfare", 180, 365, [], []),
    (CapabilityArea.LOG, "Logistics", 180, 365, [], []),
    (CapabilityArea.MIW, "Mine Warfare", 180, 365, ['ALMDS_PILOT'], []),
)

def task_codes_by_area() -> dict[CapabilityArea, list[str]]:
    out: dict[CapabilityArea, list[str]] = {a: [] for a in CapabilityArea}
    for spec in CBR_TASK_SPECS:
        out[spec.capability_area].append(spec.code)
    return out


def catalog_stats() -> dict:
    by_area = {a.value: 0 for a in CapabilityArea}
    anchors = 0
    for s in CBR_TASK_SPECS:
        by_area[s.capability_area.value] += 1
        if s.is_anchor_task:
            anchors += 1
    return {
        "total_tasks": len(CBR_TASK_SPECS),
        "anchor_tasks": anchors,
        "by_area": by_area,
    }
